vim.api.nvim_set_hl(0, 'Scrollbar', { fg = "#f6f8fa", bg = "#1d2328" })
vim.api.nvim_set_hl(0, 'StatusLine_bg', { link = "Normal" })
-- vim.api.nvim_set_hl(0, 'StatusLine_bg', { bg = "#ffffff" })
vim.api.nvim_set_hl(0, 'StatusLine_Normal', { bg = "#1d2328", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeNormal', { bg = "#0969da", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeInsert', { bg = "#1a7f37", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeVisual', { bg = "#bc4c00", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeReplace', { bg = "#c4432b", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeCommand', { bg = "#bf3989", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeTerminal', { bg = "#1a7f37", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'StatusLine_Column', { fg = "#424a53", bg = "#f6f8fa" })
vim.api.nvim_set_hl(0, 'StatusLine_FileName', { bg = "#ffffff", fg = "#a89984" })
vim.api.nvim_set_hl(0, 'StatusLine_WordChars', { bg = "#ffffff", fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'StatusLine_GitStatus', { bg = "#665c54", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'StatusLine_Separatror', { fg = "#0969da", bg = "#f6f8fa" })


