vim.api.nvim_set_hl(0, 'Scrollbar', { fg = "#1d2328", bg = "#afb8c1" })
vim.api.nvim_set_hl(0, 'StatusLine_bg', { link = "Normal" })
-- vim.api.nvim_set_hl(0, 'StatusLine_bg', { bg = "#ffffff" })
vim.api.nvim_set_hl(0, 'StatusLine_Normal', { bg = "#1d2328", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeNormal', { bg = "#0969da", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeInsert', { bg = "#1a7f37", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeVisual', { bg = "#bc4c00", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeReplace', { bg = "#c4432b", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeCommand', { bg = "#bf3989", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'ModeTerminal', { bg = "#1a7f37", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'StatusLine_Column', { fg = "#ffffff", bg = "#1d2328" })
vim.api.nvim_set_hl(0, 'StatusLine_FileName', { bg = "#ffffff", fg = "#1d2328" })
vim.api.nvim_set_hl(0, 'StatusLine_WordChars', { bg = "#ffffff", fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'StatusLine_GitStatus', { bg = "#1d2328", fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'StatusLine_Separatror', { fg = "#0969da", bg = "#1d2328" })
